set -g default-terminal "${TERM}"
set -ga terminal-overrides ",xterm-256color:Tc"

# set -g status-style 'bg=#070099 fg=#ffffff'
unbind C-b
set-option -g prefix C-a

# resize panes
bind -r h resize-pane -L 5   # 5 px bigger to the left
bind -r j resize-pane -D 5   # 5 px bigger down
bind -r k resize-pane -U 5   # 5 px bigger up
bind -r l resize-pane -R 5   # 5 px bigger right
setw -g mode-keys vi

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'

run '~/.tmux/plugins/tpm/tpm'
